In [9]:
import pandas as pd
import numpy as np
import re

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [5]:
print("PROCESSING DATA")
tstFilep = "posFeaturesTest.csv"
baseFilep = "posFeatures.csv"
trainFilep = pd.read_csv(baseFilep, low_memory=False)
testFilep = pd.read_csv(tstFilep, low_memory=False)

drop = ['swda_filename','ptb_basename','conversation_no','transcript_index','act_tag',
        'caller','cleanText','action','fillers','utterance_index','subutterance_index','text']
# trainFilep = trainFilep.drop(drop, axis = 1)
# testFilep = testFilep.drop(drop, axis = 1)
print(trainFilep.shape)
print(testFilep.shape)


print("PROCESSING DATA")
tstFilec = "customFeaturesTest.csv"
baseFilec = "customFeatures.csv"
trainFilec = pd.read_csv(baseFilec, low_memory=False)
testFilec = pd.read_csv(tstFilec, low_memory=False)
# trainFilec = trainFilec.drop(drop, axis = 1)
# testFilec = testFilec.drop(drop, axis = 1)
print(trainFilec.shape)
print(testFilec.shape)

print("PROCESSING DATA")
tstFile = "TopTenTest.csv"
baseFile = "TopTenTrain.csv"
trainFile = pd.read_csv(baseFile, low_memory=False)
testFile = pd.read_csv(tstFile, low_memory=False)
print(trainFile.shape)
print(testFile.shape)

print("PROCESSING DATA")
tstFileu = "unigramFeaturesTest.csv"
baseFileu = "unigramFeatures.csv"
trainFileu = pd.read_csv(baseFileu, low_memory=False)
testFileu = pd.read_csv(tstFileu, low_memory=False)
# trainFileu = trainFileu.drop(drop, axis = 1)
# testFileu = testFileu.drop(drop, axis = 1)
print(trainFileu.shape)
print(testFileu.shape)



PROCESSING DATA
(147510, 46)
(26540, 46)
PROCESSING DATA
(147510, 86)
(26540, 86)
PROCESSING DATA
(147510, 104)
(26540, 104)
PROCESSING DATA
(147510, 714)
(26540, 714)


In [6]:
# trainFile = pd.concat([trainFile, trainFileu, trainFilep, trainFilec], axis = 1)
# testFile = pd.concat([testFile, testFileu, testFilep, testFilec], axis = 1)
# print(trainFile.shape)
# print(testFile.shape)

In [7]:
# current = 'sd'
# current = 'b'
# current = 'sv'
# current = '%'
# current = 'aa'
# current = 'ba'
# current = 'qy'
# current = 'x'
# current = 'ny'
# current = 'fc'
feats = ['sd', 'b', 'sv', '%', 'aa', 'ba', 'qy', 'x', 'ny', 'fc']

In [70]:
# print("PROCESSING DATA")
# tstFile = "TopTenTest.csv"
# baseFile = "TopTenTrain.csv"
# trainFile = pd.read_csv(baseFile, low_memory=False)
# testFile = pd.read_csv(tstFile, low_memory=False)



In [71]:


# features = ['WC','WPS']
features = ['Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep',
         'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect',
         'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc',
         'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body',
         'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast',
         'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money',
         'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma',
         'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']
print("baseline with only LIWC features: ", features)


for feat in feats:
    current = feat

    trtags = list(trainFile["act_tag"])
    for x in range(len(trtags)):
        t = trtags[x]
        if t != current:
            trtags[x] = 0
        else:
            trtags[x] = 1

    trtags = np.array(trtags)
#     print(trtags.shape)

    tstags = list(testFile["act_tag"])
    for x in range(len(tstags)):
        t = tstags[x]
        if t != current:
            tstags[x] = 0
        else:
            tstags[x] = 1
    tstags = np.array(tstags)
#     print(tstags.shape)


    trainer = []
    tester = []
    for thing in features:
        feattr = np.array(trainFile[thing])
        trainer.append(feattr)

        featts = np.array(testFile[thing])
        tester.append(featts)
#     print(trainer[:2])
#     print(tester.shape)
    trainer = np.array(trainer).T
    tester = np.array(tester).T
#     print(trainer.shape)
#     print(tester.shape)
    
#     break

    clf = LogisticRegression(random_state=0, solver='liblinear',multi_class='ovr').fit(trainer, trtags)
    print(current, clf.score(tester, tstags))
#     break

baseline with only LIWC features:  ['Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']
sd 0.8255463451394122
b 0.9331574981160512
sv 0.8539562923888471
% 0.9412961567445366
aa 0.9632629992464204
ba 0.976036171816

In [72]:
# print("PROCESSING DATA")
# tstFile = "unigramFeaturesTest.csv"
# baseFile = "unigramFeatures.csv"
# trainFile = pd.read_csv(baseFile, low_memory=False)
# testFile = pd.read_csv(tstFile, low_memory=False)


In [73]:

# features = ['WC','WPS']
features = ['able', 'about', 'absolutely', 'actually', 'afford', 'after', 'again', 'against', 'age', 'ago',
            'agree', 'ahead', 'air', 'all', 'almost', 'along', 'already', 'also', 'although', 'always', 'am',
            'american', 'amount', 'an', 'and', 'another', 'any', 'anybody', 'anymore', 'anything', 'anyway',
            'are', 'area', 'areas', 'arent', 'around', 'as', 'at', 'away', 'awful', 'baby', 'back', 'bad',
            'basically', 'be', 'beautiful', 'because', 'become', 'been', 'before', 'being', 'believe',
            'benefits', 'best', 'bet', 'better', 'between', 'big', 'bit', 'book', 'books', 'both',
            'bought', 'boy', 'bring', 'brother', 'budget', 'built', 'business', 'but', 'buy', 'buying',
            'by', 'bye', 'call', 'called', 'came', 'camping', 'can', 'cans', 'cant', 'capital', 'car', 'card',
            'cards', 'care', 'cars', 'case', 'cases', 'catch', 'cause', 'certain', 'certainly', 'chance',
            'change', 'changed', 'changes', 'check', 'child', 'children', 'city', 'class', 'close', 'cold',
            'college', 'come', 'comes', 'coming', 'community', 'companies', 'company', 'computer', 'concerned',
            'control', 'cook', 'cost', 'could', 'couldnt', 'countries', 'country', 'couple', 'course', 'credit',
            'crime', 'cut', 'dallas', 'daughter', 'day', 'days', 'deal', 'death', 'decided', 'definitely', 'did',
            'didnt', 'difference', 'different', 'difficult', 'dinner', 'do', 'does', 'doesnt', 'dog', 'doing',
            'dollars', 'done', 'dont', 'door', 'down', 'drive', 'drug', 'drugs', 'during', 'each', 'early',
            'easier', 'easy', 'eat', 'education', 'eight', 'eighty', 'either', 'else', 'end', 'ended', 'enjoy',
            'enjoyed', 'enough', 'especially', 'even', 'ever', 'every', 'everybody', 'everyone', 'everything',
            'exactly', 'example', 'except', 'exercise', 'expensive', 'experience', 'extra', 'fact', 'fairly', 
            'family', 'fan', 'far', 'father', 'favorite', 'feel', 'felt', 'few', 'fifteen', 'fifty', 'figure',
            'finally', 'find', 'fine', 'first', 'fish', 'five', 'food', 'football', 'for', 'forth', 'forty',
            'found', 'four', 'free', 'friend', 'friends', 'from', 'front', 'full', 'fun', 'funny', 'game',
            'gave', 'get', 'gets', 'getting', 'give', 'go', 'god', 'goes', 'going', 'gone', 'good', 'goodness',
            'gosh', 'got', 'gotten', 'government', 'great', 'grew', 'group', 'growing', 'guess', 'gun', 'guy',
            'guys', 'had', 'half', 'hand', 'happen', 'happened', 'happens', 'happy', 'hard', 'has', 'hate',
            'have', 'havent', 'having', 'he', 'health', 'hear', 'heard', 'help', 'her', 'here', 'hes', 'high',
            'him', 'his', 'hit', 'home', 'homes', 'hope', 'hot', 'hour', 'hours', 'house', 'how', 'huh',
            'hundred', 'husband', 'id', 'idea', 'if', 'ill', 'im', 'imagine', 'important', 'in', 'income',
            'information', 'instead', 'insurance', 'interest', 'interested', 'interesting', 'into', 'involved',
            'is', 'isnt', 'issue', 'it', 'its', 'ive', 'job', 'jury', 'just', 'keep', 'kept', 'kid', 'kids',
            'kind', 'kinds', 'knew', 'know', 'large', 'last', 'late', 'lately', 'later', 'law', 'learn', 'least',
            'leave', 'left', 'less', 'let', 'lets', 'level', 'life', 'like', 'liked', 'likes', 'line', 'listen',
            'little', 'live', 'lived', 'lives', 'living', 'local', 'long', 'longer', 'look', 'looked', 'looking',
            'looks', 'lost', 'lot', 'lots', 'love', 'made', 'major', 'make', 'makes', 'making', 'man', 'many',
            'married', 'matter', 'may', 'maybe', 'me', 'mean', 'men', 'middle', 'might', 'miles', 'mind', 'mine',
            'minutes', 'money', 'month', 'months', 'more', 'morning', 'most', 'mostly', 'mother', 'move', 'moved',
            'movie', 'movies', 'much', 'music', 'must', 'my', 'myself', 'name', 'neat', 'need', 'needed', 'needs',
            'never', 'new', 'news', 'newspaper', 'next', 'nice', 'night', 'nine', 'nineteen', 'ninety', 'no',
            'not', 'nothing', 'now', 'number', 'nursing', 'of', 'off', 'often', 'oh', 'okay', 'old', 'older',
            'on', 'once', 'one', 'ones', 'only', 'or', 'other', 'ought', 'our', 'ours', 'out', 'outside', 'over',
            'own', 'paid', 'paper', 'parents', 'part', 'particular', 'past', 'pay', 'paying', 'people', 'percent',
            'person', 'phone', 'pick', 'place', 'places', 'plan', 'plano', 'play', 'playing', 'point', 'pretty',
            'probably', 'problem', 'problems', 'program', 'programs', 'public', 'punishment', 'put', 'putting',
            'question', 'quite', 'radio', 'rain', 'rather', 'read', 'reading', 'ready', 'real', 'realize', 
            'really', 'reason', 'recently', 'recycling', 'regular', 'remember', 'right', 'room', 'run', 'running',
            'said', 'same', 'saw', 'say', 'saying', 'says', 'school', 'schools', 'second', 'see', 'seem',
            'seems', 'seen', 'sell', 'send', 'sense', 'service', 'set', 'seven', 'seventy', 'several', 'she',
            'shes', 'short', 'should', 'show', 'shows', 'side', 'since', 'sister', 'sit', 'sitting', 'situation',
            'six', 'sixty', 'small', 'so', 'society', 'some', 'somebody', 'someone', 'something', 'sometimes',
            'somewhere', 'son', 'soon', 'sort', 'sounds', 'spend', 'spent', 'start', 'started', 'starting',
            'state', 'stay', 'still', 'story', 'stuff', 'such', 'summer', 'supposed', 'sure', 'system', 'take',
            'taken', 'takes', 'taking', 'talk', 'talked', 'talking', 'tax', 'taxes', 'teach', 'teacher',
            'teachers', 'team', 'television', 'tell', 'ten', 'tend', 'terms', 'test', 'testing', 'texas', 'th',
            'than', 'that', 'thats', 'the', 'their', 'them', 'themselves', 'then', 'there', 'theres', 'these',
            'they', 'theyd', 'theyll', 'theyre', 'theyve', 'thing', 'things', 'think', 'thinking', 'thirty',
            'this', 'those', 'though', 'thought', 'thousand', 'three', 'through', 'throw', 'time', 'times', 'to',
            'today', 'together', 'told', 'too', 'took', 'top', 'totally', 'tough', 'town', 'trees', 'tried',
            'trouble', 'true', 'try', 'trying', 'turn', 'twelve', 'twenty', 'two', 'type', 'uh', 'um', 'under',
            'understand', 'unless', 'until', 'up', 'us', 'use', 'used', 'using', 'usually', 'vacation', 'very',
            'vote', 'wait', 'walk', 'want', 'wanted', 'wants', 'war', 'was', 'wasnt', 'watch', 'watching',
            'water', 'way', 'ways', 'we', 'wear', 'weather', 'wed', 'week', 'weekend', 'weeks', 'well', 'went',
            'were', 'werent', 'weve', 'what', 'whatever', 'whats', 'when', 'where', 'whether', 'which', 'while',
            'who', 'whole', 'whos', 'why', 'wife', 'will', 'winter', 'wish', 'with', 'within', 'without',
            'woman', 'women', 'wonder', 'wonderful', 'wont', 'work', 'worked', 'working', 'works', 'world',
            'worse', 'worth', 'would', 'wouldnt', 'wow', 'wrong', 'yard', 'yeah', 'year', 'years', 'yep', 'yes',
            'yet', 'you', 'youd', 'young', 'your', 'youre', 'yourself', 'youve']
print("model with only unigram features: ", features)


for feat in feats:
    current = feat

    trtags = list(trainFileu["act_tag"])
    for x in range(len(trtags)):
        t = trtags[x]
        if t != current:
            trtags[x] = 0
        else:
            trtags[x] = 1

    trtags = np.array(trtags)
#     print(trtags.shape)

    tstags = list(testFileu["act_tag"])
    for x in range(len(tstags)):
        t = tstags[x]
        if t != current:
            tstags[x] = 0
        else:
            tstags[x] = 1
    tstags = np.array(tstags)
#     print(tstags.shape)


    trainer = []
    tester = []
    for thing in features:
        feattr = np.array(trainFileu[thing])
        trainer.append(feattr)

        featts = np.array(testFileu[thing])
        tester.append(featts)

    trainer = np.array(trainer).T
    tester = np.array(tester).T
    

#     print(trainer.shape)
#     print(tester.shape)
    clf = LogisticRegression(random_state=0, solver='liblinear',multi_class='ovr').fit(trainer, trtags)
    print(current, clf.score(tester, tstags))
#     break


model with only unigram features:  ['able', 'about', 'absolutely', 'actually', 'afford', 'after', 'again', 'against', 'age', 'ago', 'agree', 'ahead', 'air', 'all', 'almost', 'along', 'already', 'also', 'although', 'always', 'am', 'american', 'amount', 'an', 'and', 'another', 'any', 'anybody', 'anymore', 'anything', 'anyway', 'are', 'area', 'areas', 'arent', 'around', 'as', 'at', 'away', 'awful', 'baby', 'back', 'bad', 'basically', 'be', 'beautiful', 'because', 'become', 'been', 'before', 'being', 'believe', 'benefits', 'best', 'bet', 'better', 'between', 'big', 'bit', 'book', 'books', 'both', 'bought', 'boy', 'bring', 'brother', 'budget', 'built', 'business', 'but', 'buy', 'buying', 'by', 'bye', 'call', 'called', 'came', 'camping', 'can', 'cans', 'cant', 'capital', 'car', 'card', 'cards', 'care', 'cars', 'case', 'cases', 'catch', 'cause', 'certain', 'certainly', 'chance', 'change', 'changed', 'changes', 'check', 'child', 'children', 'city', 'class', 'close', 'cold', 'college', 'come', 

In [74]:
# print("PROCESSING DATA")
# tstFile = "posFeaturesTest.csv"
# baseFile = "posFeatures.csv"
# trainFile = pd.read_csv(baseFile, low_memory=False)
# testFile = pd.read_csv(tstFile, low_memory=False)


In [75]:

# features = ['WC','WPS']
features = ['cc', 'cd', 'dt', 'ex', 'fw', 'in', 'jj', 'jjr', 'jjs', 'md', 'nn', 'nnp', 
            'nnps', 'nns', 'pdt', 'pos', 'prp', 'rb', 'rbr', 'rbs', 'rp', 'sym', 
            'to', 'uh', 'vb', 'vbd', 'vbg', 'vbn', 'vbp', 'vbz', 'wdt', 'wp', 'wrb']
print("model with only pos features: ", features)


for feat in feats:
    current = feat

    trtags = list(trainFilep["act_tag"])
    for x in range(len(trtags)):
        t = trtags[x]
        if t != current:
            trtags[x] = 0
        else:
            trtags[x] = 1

    trtags = np.array(trtags)
#     print(trtags.shape)

    tstags = list(testFilep["act_tag"])
    for x in range(len(tstags)):
        t = tstags[x]
        if t != current:
            tstags[x] = 0
        else:
            tstags[x] = 1
    tstags = np.array(tstags)
#     print(tstags.shape)


    trainer = []
    tester = []
    for thing in features:
        feattr = np.array(trainFilep[thing])
        trainer.append(feattr)

        featts = np.array(testFilep[thing])
        tester.append(featts)

    trainer = np.array(trainer).T
    tester = np.array(tester).T
    

#     print(trainer.shape)
#     print(tester.shape)
    clf = LogisticRegression(random_state=0, solver='liblinear',multi_class='ovr').fit(trainer, trtags)
    print(current, clf.score(tester, tstags))
#     break


model with only pos features:  ['cc', 'cd', 'dt', 'ex', 'fw', 'in', 'jj', 'jjr', 'jjs', 'md', 'nn', 'nnp', 'nnps', 'nns', 'pdt', 'pos', 'prp', 'rb', 'rbr', 'rbs', 'rp', 'sym', 'to', 'uh', 'vb', 'vbd', 'vbg', 'vbn', 'vbp', 'vbz', 'wdt', 'wp', 'wrb']
sd 0.7530143180105501
b 0.9048605877920121
sv 0.8450263752825923
% 0.9141296156744536
aa 0.9676337603617181
ba 0.9719291635267521
qy 0.9806330067822155
x 0.9995478522984175
ny 0.984438583270535
fc 0.9853051996985682


In [76]:
# print("PROCESSING DATA")
# tstFile = "customFeaturesTest.csv"
# baseFile = "customFeatures.csv"
# trainFile = pd.read_csv(baseFile, low_memory=False)
# testFile = pd.read_csv(tstFile, low_memory=False)


In [77]:
# features = ['WC','WPS']
features = ['_laughter_', '_noise_', '_static_', '_talking_', '_tv_', 'baby_', 'baby_crying_', 'baby_talking_', 'barking_',
            'beep_', 'breathing_', 'breathing_breathing_', 'breathing_laughter_', 'child_', 'child_crying_', 'child_talking_',
            'child_yelling_', 'children_', 'children_talking_', 'clanging_', 'clicking_', 'cough_', 'dishes_', 'door_',
            'faint_', 'faintly_', 'gasp_', 'inhaling_', 'laughter_', 'laughter_breathing_', 'laughter_laughter_',
            'laughter_noise_', 'lipsmack_', 'lipsmack_breathing_', 'lipsmack_laughter_', 'mispronounced_', 'music_',
            'noise_', 'noise_laughter_', 'none', 'pause_', 'ringing_', 'rustling_', 'sigh_', 'smack_', 'sneezing_', 
            'sniffing_', 'squeak_', 'static_', 'swallowing_', 'talking_', 'throat_clearing_', 'throat_clearing_laughter_',
            'thumping_', 'tv_', 'very_faint_','very_faintly_', 'whistling_',
            '?','!',"--", '-', '+', '#', 'F','C', 'D', 'E', 'A', 'l0', 'l5', 'l15', 'l25', 'linf']
print("model with only pos features: ", features)


for feat in feats:
    current = feat

    trtags = list(trainFilec["act_tag"])
    for x in range(len(trtags)):
        t = trtags[x]
        if t != current:
            trtags[x] = 0
        else:
            trtags[x] = 1

    trtags = np.array(trtags)
#     print(trtags.shape)

    tstags = list(testFilec["act_tag"])
    for x in range(len(tstags)):
        t = tstags[x]
        if t != current:
            tstags[x] = 0
        else:
            tstags[x] = 1
    tstags = np.array(tstags)
#     print(tstags.shape)


    trainer = []
    tester = []
    for thing in features:
        feattr = np.array(trainFilec[thing])
        trainer.append(feattr)

        featts = np.array(testFilec[thing])
        tester.append(featts)

    trainer = np.array(trainer).T
    tester = np.array(tester).T
    

#     print(trainer.shape)
#     print(tester.shape)
    clf = LogisticRegression(random_state=0, solver='liblinear',multi_class='ovr').fit(trainer, trtags)
    print(current, clf.score(tester, tstags))
#     break


model with only pos features:  ['_laughter_', '_noise_', '_static_', '_talking_', '_tv_', 'baby_', 'baby_crying_', 'baby_talking_', 'barking_', 'beep_', 'breathing_', 'breathing_breathing_', 'breathing_laughter_', 'child_', 'child_crying_', 'child_talking_', 'child_yelling_', 'children_', 'children_talking_', 'clanging_', 'clicking_', 'cough_', 'dishes_', 'door_', 'faint_', 'faintly_', 'gasp_', 'inhaling_', 'laughter_', 'laughter_breathing_', 'laughter_laughter_', 'laughter_noise_', 'lipsmack_', 'lipsmack_breathing_', 'lipsmack_laughter_', 'mispronounced_', 'music_', 'noise_', 'noise_laughter_', 'none', 'pause_', 'ringing_', 'rustling_', 'sigh_', 'smack_', 'sneezing_', 'sniffing_', 'squeak_', 'static_', 'swallowing_', 'talking_', 'throat_clearing_', 'throat_clearing_laughter_', 'thumping_', 'tv_', 'very_faint_', 'very_faintly_', 'whistling_', '?', '!', '--', '-', '+', '#', 'F', 'C', 'D', 'E', 'A', 'l0', 'l5', 'l15', 'l25', 'linf']
sd 0.7925395629238885
b 0.8800678221552374
sv 0.8435568

In [81]:
# features = ['WC','WPS']
featuresc = ['_laughter_', '_noise_', '_static_', '_talking_', '_tv_', 'baby_', 'baby_crying_', 'baby_talking_', 'barking_',
            'beep_', 'breathing_', 'breathing_breathing_', 'breathing_laughter_', 'child_', 'child_crying_', 'child_talking_',
            'child_yelling_', 'children_', 'children_talking_', 'clanging_', 'clicking_', 'cough_', 'dishes_', 'door_',
            'faint_', 'faintly_', 'gasp_', 'inhaling_', 'laughter_', 'laughter_breathing_', 'laughter_laughter_',
            'laughter_noise_', 'lipsmack_', 'lipsmack_breathing_', 'lipsmack_laughter_', 'mispronounced_', 'music_',
            'noise_', 'noise_laughter_', 'none', 'pause_', 'ringing_', 'rustling_', 'sigh_', 'smack_', 'sneezing_', 
            'sniffing_', 'squeak_', 'static_', 'swallowing_', 'talking_', 'throat_clearing_', 'throat_clearing_laughter_',
            'thumping_', 'tv_', 'very_faint_','very_faintly_', 'whistling_',
            '?','!',"--", '-', '+', '#', 'F','C', 'D', 'E', 'A', 'l0', 'l5', 'l15', 'l25', 'linf']


featuresp = ['cc', 'cd', 'dt', 'ex', 'fw', 'in', 'jj', 'jjr', 'jjs', 'md', 'nn', 'nnp', 
            'nnps', 'nns', 'pdt', 'pos', 'prp', 'rb', 'rbr', 'rbs', 'rp', 'sym', 
            'to', 'uh', 'vb', 'vbd', 'vbg', 'vbn', 'vbp', 'vbz', 'wdt', 'wp', 'wrb']


featuresu = ['able', 'about', 'absolutely', 'actually', 'afford', 'after', 'again', 'against', 'age', 'ago',
            'agree', 'ahead', 'air', 'all', 'almost', 'along', 'already', 'also', 'although', 'always', 'am',
            'american', 'amount', 'an', 'and', 'another', 'any', 'anybody', 'anymore', 'anything', 'anyway',
            'are', 'area', 'areas', 'arent', 'around', 'as', 'at', 'away', 'awful', 'baby', 'back', 'bad',
            'basically', 'be', 'beautiful', 'because', 'become', 'been', 'before', 'being', 'believe',
            'benefits', 'best', 'bet', 'better', 'between', 'big', 'bit', 'book', 'books', 'both',
            'bought', 'boy', 'bring', 'brother', 'budget', 'built', 'business', 'but', 'buy', 'buying',
            'by', 'bye', 'call', 'called', 'came', 'camping', 'can', 'cans', 'cant', 'capital', 'car', 'card',
            'cards', 'care', 'cars', 'case', 'cases', 'catch', 'cause', 'certain', 'certainly', 'chance',
            'change', 'changed', 'changes', 'check', 'child', 'children', 'city', 'class', 'close', 'cold',
            'college', 'come', 'comes', 'coming', 'community', 'companies', 'company', 'computer', 'concerned',
            'control', 'cook', 'cost', 'could', 'couldnt', 'countries', 'country', 'couple', 'course', 'credit',
            'crime', 'cut', 'dallas', 'daughter', 'day', 'days', 'deal', 'death', 'decided', 'definitely', 'did',
            'didnt', 'difference', 'different', 'difficult', 'dinner', 'do', 'does', 'doesnt', 'dog', 'doing',
            'dollars', 'done', 'dont', 'door', 'down', 'drive', 'drug', 'drugs', 'during', 'each', 'early',
            'easier', 'easy', 'eat', 'education', 'eight', 'eighty', 'either', 'else', 'end', 'ended', 'enjoy',
            'enjoyed', 'enough', 'especially', 'even', 'ever', 'every', 'everybody', 'everyone', 'everything',
            'exactly', 'example', 'except', 'exercise', 'expensive', 'experience', 'extra', 'fact', 'fairly', 
            'family', 'fan', 'far', 'father', 'favorite', 'feel', 'felt', 'few', 'fifteen', 'fifty', 'figure',
            'finally', 'find', 'fine', 'first', 'fish', 'five', 'food', 'football', 'for', 'forth', 'forty',
            'found', 'four', 'free', 'friend', 'friends', 'from', 'front', 'full', 'fun', 'funny', 'game',
            'gave', 'get', 'gets', 'getting', 'give', 'go', 'god', 'goes', 'going', 'gone', 'good', 'goodness',
            'gosh', 'got', 'gotten', 'government', 'great', 'grew', 'group', 'growing', 'guess', 'gun', 'guy',
            'guys', 'had', 'half', 'hand', 'happen', 'happened', 'happens', 'happy', 'hard', 'has', 'hate',
            'have', 'havent', 'having', 'he', 'health', 'hear', 'heard', 'help', 'her', 'here', 'hes', 'high',
            'him', 'his', 'hit', 'home', 'homes', 'hope', 'hot', 'hour', 'hours', 'house', 'how', 'huh',
            'hundred', 'husband', 'id', 'idea', 'if', 'ill', 'im', 'imagine', 'important', 'in', 'income',
            'information', 'instead', 'insurance', 'interest', 'interested', 'interesting', 'into', 'involved',
            'is', 'isnt', 'issue', 'it', 'its', 'ive', 'job', 'jury', 'just', 'keep', 'kept', 'kid', 'kids',
            'kind', 'kinds', 'knew', 'know', 'large', 'last', 'late', 'lately', 'later', 'law', 'learn', 'least',
            'leave', 'left', 'less', 'let', 'lets', 'level', 'life', 'like', 'liked', 'likes', 'line', 'listen',
            'little', 'live', 'lived', 'lives', 'living', 'local', 'long', 'longer', 'look', 'looked', 'looking',
            'looks', 'lost', 'lot', 'lots', 'love', 'made', 'major', 'make', 'makes', 'making', 'man', 'many',
            'married', 'matter', 'may', 'maybe', 'me', 'mean', 'men', 'middle', 'might', 'miles', 'mind', 'mine',
            'minutes', 'money', 'month', 'months', 'more', 'morning', 'most', 'mostly', 'mother', 'move', 'moved',
            'movie', 'movies', 'much', 'music', 'must', 'my', 'myself', 'name', 'neat', 'need', 'needed', 'needs',
            'never', 'new', 'news', 'newspaper', 'next', 'nice', 'night', 'nine', 'nineteen', 'ninety', 'no',
            'not', 'nothing', 'now', 'number', 'nursing', 'of', 'off', 'often', 'oh', 'okay', 'old', 'older',
            'on', 'once', 'one', 'ones', 'only', 'or', 'other', 'ought', 'our', 'ours', 'out', 'outside', 'over',
            'own', 'paid', 'paper', 'parents', 'part', 'particular', 'past', 'pay', 'paying', 'people', 'percent',
            'person', 'phone', 'pick', 'place', 'places', 'plan', 'plano', 'play', 'playing', 'point', 'pretty',
            'probably', 'problem', 'problems', 'program', 'programs', 'public', 'punishment', 'put', 'putting',
            'question', 'quite', 'radio', 'rain', 'rather', 'read', 'reading', 'ready', 'real', 'realize', 
            'really', 'reason', 'recently', 'recycling', 'regular', 'remember', 'right', 'room', 'run', 'running',
            'said', 'same', 'saw', 'say', 'saying', 'says', 'school', 'schools', 'second', 'see', 'seem',
            'seems', 'seen', 'sell', 'send', 'sense', 'service', 'set', 'seven', 'seventy', 'several', 'she',
            'shes', 'short', 'should', 'show', 'shows', 'side', 'since', 'sister', 'sit', 'sitting', 'situation',
            'six', 'sixty', 'small', 'so', 'society', 'some', 'somebody', 'someone', 'something', 'sometimes',
            'somewhere', 'son', 'soon', 'sort', 'sounds', 'spend', 'spent', 'start', 'started', 'starting',
            'state', 'stay', 'still', 'story', 'stuff', 'such', 'summer', 'supposed', 'sure', 'system', 'take',
            'taken', 'takes', 'taking', 'talk', 'talked', 'talking', 'tax', 'taxes', 'teach', 'teacher',
            'teachers', 'team', 'television', 'tell', 'ten', 'tend', 'terms', 'test', 'testing', 'texas', 'th',
            'than', 'that', 'thats', 'the', 'their', 'them', 'themselves', 'then', 'there', 'theres', 'these',
            'they', 'theyd', 'theyll', 'theyre', 'theyve', 'thing', 'things', 'think', 'thinking', 'thirty',
            'this', 'those', 'though', 'thought', 'thousand', 'three', 'through', 'throw', 'time', 'times', 'to',
            'today', 'together', 'told', 'too', 'took', 'top', 'totally', 'tough', 'town', 'trees', 'tried',
            'trouble', 'true', 'try', 'trying', 'turn', 'twelve', 'twenty', 'two', 'type', 'uh', 'um', 'under',
            'understand', 'unless', 'until', 'up', 'us', 'use', 'used', 'using', 'usually', 'vacation', 'very',
            'vote', 'wait', 'walk', 'want', 'wanted', 'wants', 'war', 'was', 'wasnt', 'watch', 'watching',
            'water', 'way', 'ways', 'we', 'wear', 'weather', 'wed', 'week', 'weekend', 'weeks', 'well', 'went',
            'were', 'werent', 'weve', 'what', 'whatever', 'whats', 'when', 'where', 'whether', 'which', 'while',
            'who', 'whole', 'whos', 'why', 'wife', 'will', 'winter', 'wish', 'with', 'within', 'without',
            'woman', 'women', 'wonder', 'wonderful', 'wont', 'work', 'worked', 'working', 'works', 'world',
            'worse', 'worth', 'would', 'wouldnt', 'wow', 'wrong', 'yard', 'yeah', 'year', 'years', 'yep', 'yes',
            'yet', 'you', 'youd', 'young', 'your', 'youre', 'yourself', 'youve']


print("model with only pos features: ")


for feat in feats:
    current = feat

    trtags = list(trainFilec["act_tag"])
    for x in range(len(trtags)):
        t = trtags[x]
        if t != current:
            trtags[x] = 0
        else:
            trtags[x] = 1

    trtags = np.array(trtags)
#     print(trtags.shape)

    tstags = list(testFilec["act_tag"])
    for x in range(len(tstags)):
        t = tstags[x]
        if t != current:
            tstags[x] = 0
        else:
            tstags[x] = 1
    tstags = np.array(tstags)
#     print(tstags.shape)




    trainer = []
    tester = []
    for thing in featuresu:
        feattr = np.array(trainFileu[thing])
        trainer.append(feattr)

        featts = np.array(testFileu[thing])
        tester.append(featts)

    for thing in featuresp:
        feattr = np.array(trainFilep[thing])
        trainer.append(feattr)

        featts = np.array(testFilep[thing])
        tester.append(featts)

    for thing in featuresc:
        feattr = np.array(trainFilec[thing])
        trainer.append(feattr)

        featts = np.array(testFilec[thing])
        tester.append(featts)

               
        
        
    trainer = np.array(trainer).T
    tester = np.array(tester).T
    

#     print(trainer.shape)
#     print(tester.shape)

#     break
    
    
    clf = LogisticRegression(random_state=0, solver='liblinear',multi_class='ovr').fit(trainer, trtags)
    print(current, clf.score(tester, tstags))


model with only pos features: 
sd 0.8556141672946496
b 0.9499623210248681
sv 0.8732102486812359
% 0.9631122833458929
aa 0.9659758854559156
ba 0.9808967596081387
qy 0.9939713639788997
x 0.9997739261492088
ny 0.9845516201959307
fc 0.9921627731725697


In [10]:
# features = ['WC','WPS']
featuresc = ['_laughter_', '_noise_', '_static_', '_talking_', '_tv_', 'baby_', 'baby_crying_', 'baby_talking_', 'barking_',
            'beep_', 'breathing_', 'breathing_breathing_', 'breathing_laughter_', 'child_', 'child_crying_', 'child_talking_',
            'child_yelling_', 'children_', 'children_talking_', 'clanging_', 'clicking_', 'cough_', 'dishes_', 'door_',
            'faint_', 'faintly_', 'gasp_', 'inhaling_', 'laughter_', 'laughter_breathing_', 'laughter_laughter_',
            'laughter_noise_', 'lipsmack_', 'lipsmack_breathing_', 'lipsmack_laughter_', 'mispronounced_', 'music_',
            'noise_', 'noise_laughter_', 'none', 'pause_', 'ringing_', 'rustling_', 'sigh_', 'smack_', 'sneezing_', 
            'sniffing_', 'squeak_', 'static_', 'swallowing_', 'talking_', 'throat_clearing_', 'throat_clearing_laughter_',
            'thumping_', 'tv_', 'very_faint_','very_faintly_', 'whistling_',
            '?','!',"--", '-', '+', '#', 'F','C', 'D', 'E', 'A', 'l0', 'l5', 'l15', 'l25', 'linf']


featuresp = ['cc', 'cd', 'dt', 'ex', 'fw', 'in', 'jj', 'jjr', 'jjs', 'md', 'nn', 'nnp', 
            'nnps', 'nns', 'pdt', 'pos', 'prp', 'rb', 'rbr', 'rbs', 'rp', 'sym', 
            'to', 'uh', 'vb', 'vbd', 'vbg', 'vbn', 'vbp', 'vbz', 'wdt', 'wp', 'wrb']


featuresu = ['able', 'about', 'absolutely', 'actually', 'afford', 'after', 'again', 'against', 'age', 'ago',
            'agree', 'ahead', 'air', 'all', 'almost', 'along', 'already', 'also', 'although', 'always', 'am',
            'american', 'amount', 'an', 'and', 'another', 'any', 'anybody', 'anymore', 'anything', 'anyway',
            'are', 'area', 'areas', 'arent', 'around', 'as', 'at', 'away', 'awful', 'baby', 'back', 'bad',
            'basically', 'be', 'beautiful', 'because', 'become', 'been', 'before', 'being', 'believe',
            'benefits', 'best', 'bet', 'better', 'between', 'big', 'bit', 'book', 'books', 'both',
            'bought', 'boy', 'bring', 'brother', 'budget', 'built', 'business', 'but', 'buy', 'buying',
            'by', 'bye', 'call', 'called', 'came', 'camping', 'can', 'cans', 'cant', 'capital', 'car', 'card',
            'cards', 'care', 'cars', 'case', 'cases', 'catch', 'cause', 'certain', 'certainly', 'chance',
            'change', 'changed', 'changes', 'check', 'child', 'children', 'city', 'class', 'close', 'cold',
            'college', 'come', 'comes', 'coming', 'community', 'companies', 'company', 'computer', 'concerned',
            'control', 'cook', 'cost', 'could', 'couldnt', 'countries', 'country', 'couple', 'course', 'credit',
            'crime', 'cut', 'dallas', 'daughter', 'day', 'days', 'deal', 'death', 'decided', 'definitely', 'did',
            'didnt', 'difference', 'different', 'difficult', 'dinner', 'do', 'does', 'doesnt', 'dog', 'doing',
            'dollars', 'done', 'dont', 'door', 'down', 'drive', 'drug', 'drugs', 'during', 'each', 'early',
            'easier', 'easy', 'eat', 'education', 'eight', 'eighty', 'either', 'else', 'end', 'ended', 'enjoy',
            'enjoyed', 'enough', 'especially', 'even', 'ever', 'every', 'everybody', 'everyone', 'everything',
            'exactly', 'example', 'except', 'exercise', 'expensive', 'experience', 'extra', 'fact', 'fairly', 
            'family', 'fan', 'far', 'father', 'favorite', 'feel', 'felt', 'few', 'fifteen', 'fifty', 'figure',
            'finally', 'find', 'fine', 'first', 'fish', 'five', 'food', 'football', 'for', 'forth', 'forty',
            'found', 'four', 'free', 'friend', 'friends', 'from', 'front', 'full', 'fun', 'funny', 'game',
            'gave', 'get', 'gets', 'getting', 'give', 'go', 'god', 'goes', 'going', 'gone', 'good', 'goodness',
            'gosh', 'got', 'gotten', 'government', 'great', 'grew', 'group', 'growing', 'guess', 'gun', 'guy',
            'guys', 'had', 'half', 'hand', 'happen', 'happened', 'happens', 'happy', 'hard', 'has', 'hate',
            'have', 'havent', 'having', 'he', 'health', 'hear', 'heard', 'help', 'her', 'here', 'hes', 'high',
            'him', 'his', 'hit', 'home', 'homes', 'hope', 'hot', 'hour', 'hours', 'house', 'how', 'huh',
            'hundred', 'husband', 'id', 'idea', 'if', 'ill', 'im', 'imagine', 'important', 'in', 'income',
            'information', 'instead', 'insurance', 'interest', 'interested', 'interesting', 'into', 'involved',
            'is', 'isnt', 'issue', 'it', 'its', 'ive', 'job', 'jury', 'just', 'keep', 'kept', 'kid', 'kids',
            'kind', 'kinds', 'knew', 'know', 'large', 'last', 'late', 'lately', 'later', 'law', 'learn', 'least',
            'leave', 'left', 'less', 'let', 'lets', 'level', 'life', 'like', 'liked', 'likes', 'line', 'listen',
            'little', 'live', 'lived', 'lives', 'living', 'local', 'long', 'longer', 'look', 'looked', 'looking',
            'looks', 'lost', 'lot', 'lots', 'love', 'made', 'major', 'make', 'makes', 'making', 'man', 'many',
            'married', 'matter', 'may', 'maybe', 'me', 'mean', 'men', 'middle', 'might', 'miles', 'mind', 'mine',
            'minutes', 'money', 'month', 'months', 'more', 'morning', 'most', 'mostly', 'mother', 'move', 'moved',
            'movie', 'movies', 'much', 'music', 'must', 'my', 'myself', 'name', 'neat', 'need', 'needed', 'needs',
            'never', 'new', 'news', 'newspaper', 'next', 'nice', 'night', 'nine', 'nineteen', 'ninety', 'no',
            'not', 'nothing', 'now', 'number', 'nursing', 'of', 'off', 'often', 'oh', 'okay', 'old', 'older',
            'on', 'once', 'one', 'ones', 'only', 'or', 'other', 'ought', 'our', 'ours', 'out', 'outside', 'over',
            'own', 'paid', 'paper', 'parents', 'part', 'particular', 'past', 'pay', 'paying', 'people', 'percent',
            'person', 'phone', 'pick', 'place', 'places', 'plan', 'plano', 'play', 'playing', 'point', 'pretty',
            'probably', 'problem', 'problems', 'program', 'programs', 'public', 'punishment', 'put', 'putting',
            'question', 'quite', 'radio', 'rain', 'rather', 'read', 'reading', 'ready', 'real', 'realize', 
            'really', 'reason', 'recently', 'recycling', 'regular', 'remember', 'right', 'room', 'run', 'running',
            'said', 'same', 'saw', 'say', 'saying', 'says', 'school', 'schools', 'second', 'see', 'seem',
            'seems', 'seen', 'sell', 'send', 'sense', 'service', 'set', 'seven', 'seventy', 'several', 'she',
            'shes', 'short', 'should', 'show', 'shows', 'side', 'since', 'sister', 'sit', 'sitting', 'situation',
            'six', 'sixty', 'small', 'so', 'society', 'some', 'somebody', 'someone', 'something', 'sometimes',
            'somewhere', 'son', 'soon', 'sort', 'sounds', 'spend', 'spent', 'start', 'started', 'starting',
            'state', 'stay', 'still', 'story', 'stuff', 'such', 'summer', 'supposed', 'sure', 'system', 'take',
            'taken', 'takes', 'taking', 'talk', 'talked', 'talking', 'tax', 'taxes', 'teach', 'teacher',
            'teachers', 'team', 'television', 'tell', 'ten', 'tend', 'terms', 'test', 'testing', 'texas', 'th',
            'than', 'that', 'thats', 'the', 'their', 'them', 'themselves', 'then', 'there', 'theres', 'these',
            'they', 'theyd', 'theyll', 'theyre', 'theyve', 'thing', 'things', 'think', 'thinking', 'thirty',
            'this', 'those', 'though', 'thought', 'thousand', 'three', 'through', 'throw', 'time', 'times', 'to',
            'today', 'together', 'told', 'too', 'took', 'top', 'totally', 'tough', 'town', 'trees', 'tried',
            'trouble', 'true', 'try', 'trying', 'turn', 'twelve', 'twenty', 'two', 'type', 'uh', 'um', 'under',
            'understand', 'unless', 'until', 'up', 'us', 'use', 'used', 'using', 'usually', 'vacation', 'very',
            'vote', 'wait', 'walk', 'want', 'wanted', 'wants', 'war', 'was', 'wasnt', 'watch', 'watching',
            'water', 'way', 'ways', 'we', 'wear', 'weather', 'wed', 'week', 'weekend', 'weeks', 'well', 'went',
            'were', 'werent', 'weve', 'what', 'whatever', 'whats', 'when', 'where', 'whether', 'which', 'while',
            'who', 'whole', 'whos', 'why', 'wife', 'will', 'winter', 'wish', 'with', 'within', 'without',
            'woman', 'women', 'wonder', 'wonderful', 'wont', 'work', 'worked', 'working', 'works', 'world',
            'worse', 'worth', 'would', 'wouldnt', 'wow', 'wrong', 'yard', 'yeah', 'year', 'years', 'yep', 'yes',
            'yet', 'you', 'youd', 'young', 'your', 'youre', 'yourself', 'youve']


features = ['Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep',
         'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect',
         'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc',
         'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body',
         'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast',
         'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money',
         'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma',
         'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']

print("model with only pos features: ")


for feat in feats:
    current = feat

    trtags = list(trainFilec["act_tag"])
    for x in range(len(trtags)):
        t = trtags[x]
        if t != current:
            trtags[x] = 0
        else:
            trtags[x] = 1

    trtags = np.array(trtags)
#     print(trtags.shape)

    tstags = list(testFilec["act_tag"])
    for x in range(len(tstags)):
        t = tstags[x]
        if t != current:
            tstags[x] = 0
        else:
            tstags[x] = 1
    tstags = np.array(tstags)
#     print(tstags.shape)




    trainer = []
    tester = []
    for thing in featuresu:
        feattr = np.array(trainFileu[thing])
        trainer.append(feattr)

        featts = np.array(testFileu[thing])
        tester.append(featts)

    for thing in featuresp:
        feattr = np.array(trainFilep[thing])
        trainer.append(feattr)

        featts = np.array(testFilep[thing])
        tester.append(featts)

    for thing in featuresc:
        feattr = np.array(trainFilec[thing])
        trainer.append(feattr)

        featts = np.array(testFilec[thing])
        tester.append(featts)

    for thing in features:
        feattr = np.array(trainFile[thing])
        trainer.append(feattr)

        featts = np.array(testFile[thing])
        tester.append(featts)
             
        
        
    trainer = np.array(trainer).T
    tester = np.array(tester).T
    

#     print(trainer.shape)
#     print(tester.shape)

#     break
    
    
    clf = LogisticRegression(random_state=0, solver='liblinear',multi_class='ovr', max_iter=5000).fit(trainer, trtags)
    
    y_pred = clf.predict(tester)

    confusion = confusion_matrix(tstags,y_pred, labels=[1, 0])
    print(confusion)
    
    print(current, clf.score(tester, tstags))

model with only pos features: 
[[ 8741  1546]
 [ 2065 14188]]
sd 0.8639412207987943
[[ 5716   441]
 [  899 19484]]
b 0.9495101733232856
[[ 1595  2557]
 [  738 21650]]
sv 0.8758477769404672
[[ 1798   642]
 [  277 23823]]
% 0.9653730218538056
[[  340   519]
 [  445 25236]]
aa 0.9636774679728711
[[  362   394]
 [  103 25681]]
ba 0.9812735493594574
[[  404   112]
 [   30 25994]]
qy 0.9946495855312736
[[  568     1]
 [    4 25967]]
x 0.9998116051243406
[[    9   404]
 [   10 26117]]
ny 0.9844009042954032
[[  205   186]
 [    5 26144]]
fc 0.9928033157498116
